[package]
name = "spline"
version = "0.1.0"
edition = "2018"

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = 3
panic = "abort"

[dependencies]
cairo-rs = { version = "0.2", features = ["png"] }
png = "0.11"
rand = "0.6"

[[bin]]
name = "main"
path = "src/main.rs"
