[package]
name = "spline"
version = "0.1.0"
edition = "2018"

[profile.release]
opt-level = 3
lto = true
panic = "abort"

[dependencies]
png = "0.11"
cairo-rs = { version = "0.2", features = ["png"] }
rand = "0.6"

[[bin]]
name = "main"
path = "src/main.rs"
