#!/usr/bin/env bash

set -e

if [ ! "$(uname -s)" = "Linux" ]; then
    exit 1
fi

args=(
    0.5
    0.1
    8
    0
    16
    16
    350
    ../out/main.png
)

sudo sh -c "echo 1 > /proc/sys/kernel/perf_event_paranoid"
sudo sh -c "echo 0 > /proc/sys/kernel/kptr_restrict"
perf record --call-graph fp ./target/release/main "${args[@]}"
perf report
rm perf.data*

if [ -z "$1" ]; then
    exit 0
fi

valgrind --tool=cachegrind --branch-sim=yes ./target/release/main "${args[@]}"
rm cachegrind.out.*
