#!/usr/bin/env bash

set -eu

cd "$WD/dev"
rustup run nightly cargo build --release

if [ "$(uname -s)" = "Darwin" ]; then
    # http://carol-nichols.com/2017/04/20/rust-profiling-with-dtrace-on-osx/
    sudo dtrace \
        -c './target/release/main 5 5 1 out/main.png' \
        -o "$WD/prof/out.stacks" \
        -n 'profile-997 /execname == "main"/ { @[ustack(5000)] = count(); }'
    cd "$WD/prof"
    stackcollapse.pl out.stacks | flamegraph.pl > prof.svg
    rm -f out.stacks
    open prof.svg
else
    # https://blog.anp.lol/rust/2016/07/24/profiling-rust-perf-flamegraph/
    cd "$WD/prof"
    sudo sh -c 'echo 1 >/proc/sys/kernel/perf_event_paranoid'
    perf record -g "$WD/dev/target/release/main" 5 5 1 out/main.png
    perf report
    perf script | stackcollapse-perf.pl | flamegraph.pl > prof.svg
    google-chrome prof.svg
fi
